import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import { config, servicePages, siteFeatures } from "@/lib/config";
import { Button, Arrow } from "@/components/ui/Button";
export const metadata: Metadata = { title: `Our Services | ${config.name}`, description: "Explore our website, design, app, marketing, AI, and testing services. Find the right support for your business.", alternates:{canonical:"/services"}, openGraph:{title:`Our Services | ${config.name}`,description:"Design, development, and digital marketing for your business.",url:"/services"} };
export default function ServicesPage() {
  if (!siteFeatures.servicePages) notFound();
  return <><section className="service-page-hero section-container"><nav className="service-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Services</span></nav><p className="eyebrow"><span className="status-dot"/>OUR SERVICES</p><h1>Everything your business<br/><span>needs to grow online.</span></h1><div className="service-index-intro"><p>From a new website to your next campaign, find the help you need in one place. Start with one service or bring them together around your goals.</p><Button href="/#audit">Talk about your project</Button></div></section><section className="section-container service-directory" aria-labelledby="service-list-heading"><div className="service-list-header"><h2 id="service-list-heading">Find your service</h2><span>10 ways we can help</span></div><div className="service-directory-grid">{servicePages.map((service,index)=><Link href={`/services/${service.slug}`} className="service-directory-card" key={service.slug}><div className="directory-card-top"><span>{String(index+1).padStart(2,'0')}</span><Arrow diagonal/></div><h3>{service.name}</h3><p>{service.description}</p><span className="directory-card-link">Explore service <span aria-hidden="true">↗</span></span></Link>)}</div></section><section className="service-page-cta section-container"><p className="eyebrow"><span className="status-dot"/>LET’S TALK</p><h2>Not sure where to start?</h2><p>Tell us what you want to improve. We’ll help you choose the next step.</p><Button href="/#audit">Tell us about your business</Button></section></>;
}
