import { PageImage } from "@/components/pages/PageImage";
import Link from "next/link";
import { notFound } from "next/navigation";
import { blogGuides, blogSlugs, config } from "@/lib/config";
import { BlogCards } from "@/components/pages/BlogCards";
import { pageMetadata } from "@/lib/page-metadata";
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return blogSlugs.map(slug=>({slug}));}
function getPost(slug:string){const index=blogSlugs.findIndex(value=>value===slug);if(index<0)notFound();return {post:config.insights.items[index],guide:blogGuides[index]};}
export async function generateMetadata({params}:Props){const {slug}=await params;const {post}=getPost(slug);return pageMetadata(post.title,post.summary,`/blogs/${slug}`);}
export default async function BlogPage({params}:Props){const {slug}=await params;const {post,guide}=getPost(slug);const articleImage = ({"turn-visitors-into-customers":"article-visitors","keep-your-brand-consistent":"article-brand","marketing-numbers-to-track":"article-metrics"} as const)[slug as (typeof blogSlugs)[number]];const schema={"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.summary,author:{"@type":"Organization",name:config.name},mainEntityOfPage:`${config.url}/blogs/${slug}`};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><header className="inner-intro section-container blog-article-intro"><nav className="service-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/blogs">Blogs</Link><span>/</span><span aria-current="page">{post.category}</span></nav><h1>{post.title}</h1><p className="inner-lead">{post.summary}</p><span className="article-byline">By {config.name}</span></header><div className="section-container blog-article-layout"><aside><p>IN THIS BLOG</p>{guide.headings.map((heading,i)=><Link key={heading} href={`#part-${i+1}`}>{heading}</Link>)}</aside><article className="blog-article"><PageImage imageKey={articleImage} compact/>{post.paragraphs.map((paragraph,i)=><section id={`part-${i+1}`} key={paragraph}><span>0{i+1}</span><h2>{guide.headings[i]}</h2><p>{paragraph}</p></section>)}<section className="article-checklist"><h2>A quick check for your business</h2><ul>{guide.checklist.map(item=><li key={item}>{item}</li>)}</ul></section><section className="article-takeaway"><span>ONE THING TO TAKE AWAY</span><p>{guide.takeaway}</p><Link href={`/services/${guide.service}`}>Explore the related service ↗</Link></section><Link className="inner-text-link" href="/blogs">← Back to all blogs</Link></article></div><section className="inner-section section-container more-blogs"><h2>More blogs</h2><BlogCards exclude={slug}/></section></>}
