"use client";
import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { contactSchema, type ContactValues } from "@/lib/validation";
import { submitEnquiry } from "@/lib/submit-enquiry";
import { zodResolver } from "@hookform/resolvers/zod";
import { servicePages, config } from "@/lib/config";
export function ContactForm(){const [sent,setSent]=useState(false);const [error,setError]=useState("");const [company,setCompany]=useState("");const success=useRef<HTMLDivElement>(null);const {register,handleSubmit,reset,setFocus,formState:{errors,isSubmitting}}=useForm<ContactValues>({resolver:zodResolver(contactSchema),defaultValues:{name:"",email:"",service:"",message:""}});useEffect(()=>{if(sent)success.current?.focus();},[sent]);
if(sent)return <div className="contact-success" ref={success} tabIndex={-1} role="status"><span>✓</span><h2>Thank you for your enquiry.</h2><p>Your message has been received. Our team will review the details and follow up.</p><button className="button button-secondary" onClick={()=>{setSent(false);requestAnimationFrame(()=>setFocus('name'));}}>Try another enquiry ↗</button></div>;
return <form className="contact-form" noValidate onSubmit={handleSubmit(async(values)=>{setError("");try{await submitEnquiry("contact",values,company);reset();setSent(true);}catch(error){setError(error instanceof Error?error.message:"Please try again later.");}})} aria-labelledby="contact-form-title" aria-describedby="contact-demo-note"><h2 id="contact-form-title">Tell us about your project.</h2><div className="contact-form-row"><div className="form-field"><label htmlFor="contact-name">Your name</label><input id="contact-name" autoComplete="name" required maxLength={120} {...register('name')} aria-invalid={!!errors.name} aria-describedby={errors.name?'contact-name-error':undefined}/>{errors.name&&<p id="contact-name-error" className="field-error" role="alert">{errors.name.message}</p>}</div><div className="form-field"><label htmlFor="contact-email">Email address</label><input id="contact-email" type="email" autoComplete="email" required maxLength={254} {...register('email')} aria-invalid={!!errors.email} aria-describedby={errors.email?'contact-email-error':undefined}/>{errors.email&&<p id="contact-email-error" className="field-error" role="alert">{errors.email.message}</p>}</div></div><div className="form-field"><label htmlFor="contact-service">What can we help with?</label><select id="contact-service" required {...register('service')} aria-invalid={!!errors.service} aria-describedby={errors.service?'contact-service-error':undefined}><option value="">Choose a service</option>{servicePages.map(service=><option key={service.slug}>{service.name}</option>)}<option>Not sure yet</option></select>{errors.service&&<p id="contact-service-error" className="field-error" role="alert">{errors.service.message}</p>}</div><div className="form-field"><label htmlFor="contact-message">A little about your project</label><textarea id="contact-message" rows={5} required maxLength={3000} placeholder="What do you want to create or improve?" {...register('message')} aria-invalid={!!errors.message} aria-describedby={errors.message?'contact-message-error':undefined}/>{errors.message&&<p id="contact-message-error" className="field-error" role="alert">{errors.message.message}</p>}</div><div className="form-trap" aria-hidden="true"><label htmlFor="contact-company">Leave this field empty</label><input id="contact-company" value={company} onChange={event=>setCompany(event.target.value)} tabIndex={-1} autoComplete="off"/></div>{error&&<p role="alert" className="field-error">{error}</p>}<button type="submit" disabled={isSubmitting} className="button button-primary">{isSubmitting?"Sending…":"Send enquiry ↗"}</button><p className="form-note" id="contact-demo-note">We use the details you submit to respond to your enquiry. Please avoid sharing sensitive information.</p><p className="contact-brand-note">{config.name} / Design · Build · Grow</p></form>}
